---
title: "Compare-Alpha diversity"
output: html_notebook
---
#Part 2 Alpha diversity

```{r message=FALSE, warning=FALSE, include=FALSE}
library(phyloseq)
library(tidyverse)
library(dplyr)
library(microbiome)
library(hrbrthemes)
library(knitr)
library(viridis)
library(fantaxtic)
```
Three phyloseq projects from three tools:
PhySeq_Kraken_20.07.21.rds
PhySeq_Braken_20.07.21.rds
PhySeq_Metaphlan_20.07.21.rds
```{r}
PhySeq_Kraken_20.07.21 <- readRDS("Kraken/PhySeq_Kraken_20.07.21.rds")
PhySeq_Braken_20.07.21 <- readRDS("Kraken-Braken/PhySeq_Braken_20.07.21.rds")
PhySeq_Metaphlan_20.07.21 <- readRDS("Metaphlan3/PhySeq_Metaphlan_20.07.21.rds")
```

Phyloseq project prepare
```{r}
#kraken
aggre_kraken_phy <- aggregate_taxa(PhySeq_Kraken_20.07.21,"species") %>% aggregate_rare(level = "species", detection = 0.1/100, prevalence = 1/100)
infant_aggre_kraken_phy <- subset_samples(aggre_kraken_phy, !(sample_type %in% c("F","M"))) %>% microbiome::transform(transform = "compositional")
#kraken_allknown
aggre_kraken_allknown_phy <- aggregate_taxa(PhySeq_Kraken_20.07.21,"species") %>% aggregate_rare(level = "species", detection = 0.1/100, prevalence = 1/100) %>% subset_taxa(!(species=="Unknown"))
infant_aggre_kraken_allknown_phy <- subset_samples(aggre_kraken_allknown_phy, !(sample_type %in% c("F","M"))) %>% microbiome::transform(transform = "compositional")
#Braken
aggre_braken_phy <- aggregate_taxa(PhySeq_Braken_20.07.21,"species") %>% aggregate_rare(level = "species", detection = 0.1/100, prevalence = 1/100)
infant_aggre_braken_phy <- subset_samples(aggre_braken_phy, !(sample_type %in% c("F","M"))) %>% microbiome::transform(transform = "compositional")
#Metaphlan
aggre_meta_phy <- aggregate_taxa(PhySeq_Metaphlan_20.07.21,"species") %>% aggregate_rare(level = "species", detection = 0.1/100, prevalence = 1/100)
infant_aggre_meta_phy <- subset_samples(aggre_meta_phy, !(sample_type %in% c("F","M"))) %>% microbiome::transform(transform = "compositional")
```

Alpha diversity
```{r}
#kraken
alpha__kraken <-microbiome::alpha(infant_aggre_kraken_phy, index = c("observed","shannon","chao1"))
kable(head(alpha__kraken))
#kraken_allknown
alpha__kraken_allknown <-microbiome::alpha(infant_aggre_kraken_allknown_phy, index = c("observed","shannon","chao1"))
kable(head(alpha__kraken_allknown))
#braken
alpha__braken <-microbiome::alpha(infant_aggre_braken_phy, index = c("observed","shannon","chao1"))
kable(head(alpha__braken))
#meta
alpha__meta <-microbiome::alpha(infant_aggre_meta_phy, index = c("observed","shannon","chao1"))
kable(head(alpha__meta))
```

boxplot by time flow
```{r}
#kraken
sample_kraken <- sample_data(infant_aggre_kraken_phy)
box_kraken <- merge(sample_kraken, alpha__kraken, by = 0) %>% data.frame()

p_box_kraken <- box_kraken %>% ggplot(aes(x=sample_type, y=diversity_shannon)) +
  geom_boxplot() +
  geom_jitter(color="black", size=0.6, alpha=0.9)+
  labs(title = "Kraken", caption = "shannon") +
  ylim(c(0,4)) +
  theme(plot.title = element_text(size=11))
print(p_box_kraken)

#kraken_allknown
sample_kraken_allknown <- sample_data(infant_aggre_kraken_allknown_phy)
box_kraken_allknown <- merge(sample_kraken_allknown, alpha__kraken_allknown, by = 0) %>% data.frame()

p_box_kraken_allknown <- box_kraken_allknown %>% ggplot(aes(x=sample_type, y=diversity_shannon)) +
  geom_boxplot() +
  geom_jitter(color="black", size=0.6, alpha=0.9)+
  labs(title = "Kraken_allknown", caption = "shannon") +
  ylim(c(0,4)) +
  theme(plot.title = element_text(size=11))
print(p_box_kraken_allknown)

#braken
sample_braken <- sample_data(infant_aggre_braken_phy)
box_braken <- merge(sample_braken, alpha__braken, by = 0) %>% data.frame()

p_box_braken <- box_braken %>% ggplot(aes(x=sample_type, y=diversity_shannon)) +
  geom_boxplot() +
  geom_jitter(color="black", size=0.6, alpha=0.9)+
  labs(title = "Braken", caption = "shannon") +
  ylim(c(0,4)) +
  theme(plot.title = element_text(size=11))
print(p_box_braken)

#meta
sample_meta <- sample_data(infant_aggre_meta_phy)
box_meta <- merge(sample_meta, alpha__meta, by = 0) %>% data.frame()

p_box_meta <- box_meta %>% ggplot(aes(x=sample_type, y=diversity_shannon)) +
  geom_boxplot() +
  geom_jitter(color="black", size=0.6, alpha=0.9)+
  labs(title = "Meta", caption = "shannon") +
  ylim(c(0,4)) +
  theme(plot.title = element_text(size=11))
print(p_box_meta)
```

boxplot compare
```{r}

```



top taxa by time point
```{r}
taxa_kraken <- get_top_taxa(infant_aggre_kraken_phy, 10)
taxa_table <- 
```


